name = "workers-ai-inpaint"
main = "src/worker.ts"
compatibility_date = "2024-11-01"


[ai]
# بایندینگ پیش‌فرض Workers AI
binding = "AI"


[vars]
# اندازه خروجی پیش‌فرض
OUTPUT_SIZE = "768x768"